#pragma once

#define MASTER_RIGHT

#define TAPPING_TERM 190
#define TAPPING_TERM_PER_KEY

#define ONESHOT_TAP_TOGGLE 3
#define ONESHOT_TIMEOUT 1500

#define MOUSEKEY_MAX_SPEED 5
#define MOUSEKEY_DELAY 10
#define MOUSEKEY_INTERVAL 16

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_TASK_THROTTLE_MS 1
#define POINTING_DEVICE_INVERT_X

#define OS_DETECTION_DEBOUNCE 400
#define OS_DETECTION_KEYBOARD_RESET
